const CLIENT_INFO_KEY_PREFIX = 'user:';
const ROOM_INFO_KEY_PREFIX = 'room:';
const QUESTION_KEY_PREFIX = 'question:';
const GROUP_NAME_SUFFIX = '-group';

export { CLIENT_INFO_KEY_PREFIX, ROOM_INFO_KEY_PREFIX, QUESTION_KEY_PREFIX, GROUP_NAME_SUFFIX };
